### ISSUE TITLE
Issue with load_custom_map LDAP sync

### ISSUE THREAD

**Issue by benhocker** [github/ldap-teamsync#78]
In the example [syncmap.yml.example](https://github.com/github/ldap-teamsync/blob/main/syncmap.yml.example#L4), it is referring to the LDAP group by a key of `ldap:` but in the [load_custom_map method](https://github.com/github/ldap-teamsync/blob/main/app.py#L228) it is looking for a key of `directory:`.  Which is the proper key and I'll submit a PR for fixing the code or documentation?

Once I updated my syncmap.yml to look like this, the syncs started working:

```yaml
---
mapping:
  - github: team1
    directory: ldapgroup1
  - github: team2
    directory: ldapgroup2
```
